const $=id=>document.getElementById(id),form=$('settings'),status=$('status');
const money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n):'—';
const pct=n=>Number.isFinite(n)?(n*100).toFixed(2)+'%':'—',num=n=>Number.isFinite(n)?n.toFixed(2):'—';
const compact=n=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
const names={crowd10:'CrowdCent · 10-day',crowd30:'CrowdCent · 30-day',numerai:'Numerai'};
let meta,result,worker,busy=false,page=0,active='overview';
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function config(){const f=new FormData(form);return{source:f.get('source'),longs:+f.get('longs'),shorts:+f.get('shorts'),holding:+f.get('holding'),entryHour:+f.get('entryHour'),signalLag:+f.get('signalLag'),mode:f.get('mode'),capital:+f.get('capital'),notional:+f.get('notional'),leverage:+f.get('leverage'),start:f.get('start'),end:f.get('end'),fee:+f.get('feeBps')/10000,liqFee:+f.get('liqBps')/10000,rf:+f.get('rfPct')/100,delay:+f.get('delay'),defaultMax:+f.get('defaultMax'),closeEnd:f.has('closeEnd'),fallback:f.has('fallback')};}
function hints(){const c=config();$('lev-label').value=c.leverage+'×';$('margin-hint').textContent=`${money(c.notional/c.leverage)} collateral per order, before fees. Notional is exposure; leverage changes required collateral.`;}
form.addEventListener('input',()=>{hints();if(result&&!busy){status.textContent='Settings changed. Run the backtest to update results.';status.className='status stale';}});
function coverage(resetDates=false){if(!meta)return;const s=meta.sources[$('source').value];$('start').min=s.start;$('end').min=s.start;$('start').max=meta.end.slice(0,10);$('end').max=meta.end.slice(0,10);if(resetDates){$('start').value=s.start;$('end').value=s.end;}$('coverage').textContent=`Signals: ${s.start} to ${s.end} · ${s.days} daily snapshots. Market history through ${meta.end.slice(0,10)}.`;}
$('source').addEventListener('change',()=>coverage(true));
$('reset').onclick=()=>{form.reset();hints();coverage(true);if(result){status.textContent='Defaults restored. Run the backtest to update results.';status.className='status stale';}};
function setBusy(value){busy=value;$('run').disabled=value;$('reset').disabled=value;for(const el of form.elements)if(el.id!=='run'&&el.id!=='reset')el.disabled=value;$('results').setAttribute('aria-busy',String(value));$('run').innerHTML=value?'Computing…':'Run backtest <span>↗</span>';}
function run(e){e?.preventDefault();if(busy||!meta)return;if(!form.reportValidity())return;const c=config();if(c.start>c.end){status.textContent='The start date must be on or before the end date.';status.className='status error';return;}
 if(!worker){worker=new Worker('./worker.js',{type:'module'});worker.onmessage=({data:m})=>{if(m.type==='progress'){status.textContent=`Loading historical prices and funding… ${Math.round(m.value*100)}%`;return;}setBusy(false);if(m.type==='error'){status.textContent=m.message;status.className='status error';return;}result=m.result;page=0;render();};worker.onerror=e=>{setBusy(false);status.textContent='The calculation could not finish. Please reload and try again.';status.className='status error';worker.terminate();worker=null;};}
 setBusy(true);status.className='status';status.textContent=result?'Calculating portfolio performance…':'Loading the historical snapshot (about 35 MB, once per session)…';worker.postMessage({config:c});}
form.onsubmit=run;
function render(){const {metrics:m,config:c,quality:q}=result;$('export').disabled=false;
 $('run-description').textContent=`${names[c.source]} · ${c.longs} longs + ${c.shorts} shorts · ${c.mode} · ${c.leverage}× · ${c.start} — ${c.end}`;
 status.className='status';status.textContent=`${m.trades.toLocaleString()} executed orders · ${result.skips.length.toLocaleString()} skipped signals · ${m.liqCount} liquidations · ${m.days.toFixed(1)} days analyzed${q.halted?' · Stopped: account equity depleted':''}${q.missingFunding?' · Missing funding records: see Method & data':''}${c.signalLag===0?' · Same-day signals: publication timing unverified':''}`;
 if(q.halted)status.className='status error';
 $('metrics').innerHTML=[['Net PnL',money(m.net),'After funding and fees',m.net],['Total return',pct(m.totalReturn),`Final equity ${money(m.final)}`,m.totalReturn],['Sharpe ratio',num(m.sharpe),'Daily · annualized',m.sharpe],['Max drawdown',pct(m.maxDD),'Hourly account equity',m.maxDD]].map(([label,v,h,n])=>`<article><span>${label}</span><strong class="${n<0?'negative':''}">${v}</strong><small>${h}</small></article>`).join('');
 $('metric-table').innerHTML=[['CAGR',pct(m.cagr)],['Sortino ratio',num(m.sortino)],['Annualized volatility',pct(m.volatility)],['Calmar ratio',num(m.calmar)],['Funding PnL',money(m.funding)],['Trading fees',money(m.fees)]].map(([k,v])=>`<div class="metric-row"><span>${k}</span><b>${v}</b></div>`).join('');
 const last=result.rows.at(-1);$('decomp').innerHTML=[['Price PnL',last?.pricePnl||0],['Funding',m.funding],['Fees',-m.fees],['Net PnL',m.net]].map(([k,v])=>`<div><span>${k}</span><b class="${v<0?'negative':'positive'}">${money(v)}</b></div>`).join('');
 $('risk-metrics').innerHTML=[['Closing-event win rate',pct(m.winRate)],['Closing-event profit factor',num(m.profitFactor)],['Closing events',m.closed],['Liquidation events',m.liqCount],['Executed orders',m.trades],['Total traded notional',money(m.turnover)],['Best daily return',pct(Math.max(...result.daily.map(d=>d.return??0)))],['Worst daily return',pct(Math.min(...result.daily.map(d=>d.return??0)))],['Positions still open',m.open]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');
 $('trade-caption').textContent='Includes entries, adds, reductions, timed exits and final closes. Exports include every event.';
 $('data-quality').innerHTML=`<div class="quality"><p><b>Snapshot:</b> ${meta.start.slice(0,10)} — ${meta.end.slice(0,10)} · ${meta.symbols.length} symbols · hourly data</p><p><b>This run:</b> ${q.fallbackBars.toLocaleString()} held-position hours with oracle fallback candles; ${q.staleMarks.toLocaleString()} held-position hours with stale marks.</p><p><b>Funding coverage:</b> ${q.missingFunding.toLocaleString()} held-position hours without a funding record; ${q.oracleFallback.toLocaleString()} funding payments without an oracle price.</p><p><b>Annualization:</b> ${m.days.toFixed(1)} days of history. ${m.days<365?'CAGR extrapolates a period shorter than a year.':'365-day basis.'}</p></div>`;
 drawActive();}
function chart(id,rows,series,{percent=false,baseline=null}={}){const el=$(id);if(!rows.length){el.innerHTML='<div class="placeholder">No observations in this window.</div>';return;}
 const width=Math.max(310,el.clientWidth||600),height=el.clientHeight||240,left=60,right=17,top=20,bottom=36,w=width-left-right,h=height-top-bottom;
 let vals=rows.flatMap(r=>series.map(s=>r[s.key])).filter(Number.isFinite);if(baseline!==null)vals.push(baseline);
 let lo=Math.min(...vals),hi=Math.max(...vals);if(!Number.isFinite(lo)){el.innerHTML='<div class="placeholder">No values available.</div>';return;}
 const pad=(hi-lo||Math.max(1,Math.abs(hi)*.01))*.12;lo-=pad;hi+=pad;
 const x=i=>left+i/Math.max(1,rows.length-1)*w,y=v=>top+(hi-v)/(hi-lo)*h;
 const tick=v=>percent?(v*100).toFixed(1)+'%':compact(v);
 const ticks=Array.from({length:5},(_,i)=>lo+(hi-lo)*i/4);
 let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(series.map(s=>s.name).join(', '))} over the backtest period"><defs><linearGradient id="${id}-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${series[0].color}" stop-opacity=".15"/><stop offset="100%" stop-color="${series[0].color}" stop-opacity="0"/></linearGradient></defs>`;
 for(const v of ticks)svg+=`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e9eeee"/><text x="${left-10}" y="${y(v)+4}" text-anchor="end">${tick(v)}</text>`;
 if(baseline!==null)svg+=`<line x1="${left}" x2="${width-right}" y1="${y(baseline)}" y2="${y(baseline)}" stroke="#a9bfba" stroke-dasharray="4 4"/>`;
 series.forEach((s,j)=>{const points=rows.map((r,i)=>`${x(i).toFixed(1)},${y(r[s.key]).toFixed(2)}`).join(' ');if(series.length===1)svg+=`<polygon points="${left},${top+h} ${points} ${x(rows.length-1)},${top+h}" fill="url(#${id}-fill)"/>`;svg+=`<polyline fill="none" stroke="${s.color}" stroke-width="1.8" stroke-linejoin="round" points="${points}"/>`;});
 for(let t=0;t<4;t++){const i=Math.round(t/3*(rows.length-1)),d=new Date((result.epoch+rows[i].hour)*3600000);svg+=`<text x="${x(i)}" y="${height-9}" text-anchor="${t===0?'start':t===3?'end':'middle'}">${d.toLocaleDateString('en-GB',{month:'short',day:'numeric',timeZone:'UTC'})}</text>`;}
 svg+='<line class="cursor" y1="'+top+'" y2="'+(top+h)+'" stroke="#6e9c93" stroke-dasharray="3 3" visibility="hidden"/></svg>';el.innerHTML=svg;
 if(series.length>1)el.insertAdjacentHTML('beforeend',`<div style="position:absolute;top:0;right:15px;font-size:11px;background:#fffe">${series.map(s=>`<span style="color:${s.color};margin-left:12px">━ ${s.name}</span>`).join('')}</div>`);
 el.onpointermove=e=>{const rect=el.getBoundingClientRect(),i=Math.max(0,Math.min(rows.length-1,Math.round((e.clientX-rect.left-left)/w*(rows.length-1)))),r=rows[i],cursor=el.querySelector('.cursor');cursor.setAttribute('x1',x(i));cursor.setAttribute('x2',x(i));cursor.setAttribute('visibility','visible');const tip=$('tooltip');tip.textContent=new Date((result.epoch+r.hour)*3600000).toISOString().slice(0,16).replace('T',' ')+' UTC\n'+series.map(s=>`${s.name}: ${percent?pct(r[s.key]):money(r[s.key])}`).join('\n');tip.hidden=false;tip.style.left=Math.max(8,Math.min(innerWidth-230,e.clientX+15))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-130,e.clientY-80))+'px';};
 el.onpointerleave=()=>{$('tooltip').hidden=true;el.querySelector('.cursor')?.setAttribute('visibility','hidden');};}
function histogram(){const el=$('hist-chart'),r=result.daily.map(d=>d.return).filter(Number.isFinite);if(!r.length){el.innerHTML='<div class="placeholder">No daily returns.</div>';return;}const count=20,min=Math.min(...r),max=Math.max(...r),span=max-min||.002,lo=min===max?min-span/2:min,step=span/count,bins=Array(count).fill(0);for(const v of r)bins[Math.min(count-1,Math.max(0,Math.floor((v-lo)/step)))]++;const width=Math.max(310,el.clientWidth),height=el.clientHeight,left=36,bottom=35,top=18,w=width-left-18,h=height-top-bottom,m=Math.max(...bins,1);let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Histogram of daily percentage returns">`;for(let j=0;j<=3;j++){let v=m*j/3,y=top+h-v/m*h;svg+=`<line x1="${left}" x2="${width-18}" y1="${y}" y2="${y}" stroke="#edf0f0"/><text x="${left-8}" y="${y+4}" text-anchor="end">${Math.round(v)}</text>`;}bins.forEach((n,i)=>{svg+=`<rect x="${left+i*w/count+1}" y="${top+h-n/m*h}" width="${w/count-2}" height="${n/m*h}" rx="2" fill="${lo+(i+.5)*step<0?'#ca8290':'#57ad99'}"><title>${pct(lo+i*step)} to ${pct(lo+(i+1)*step)}: ${n} days</title></rect>`;});for(let j=0;j<3;j++)svg+=`<text x="${left+j/2*w}" y="${height-10}" text-anchor="${j===0?'start':j===2?'end':'middle'}">${pct(lo+j/2*span)}</text>`;el.innerHTML=svg+'</svg>';}
function monthly(){const months={};for(const d of result.daily){const key=d.day.slice(0,7);months[key]=(months[key]??1)*(1+(d.return??0));}const entries=Object.entries(months).map(([k,v])=>[k,v-1]),max=Math.max(.001,...entries.map(r=>Math.abs(r[1])));$('monthly').innerHTML=entries.map(([k,v])=>`<div class="month-row"><span>${k}</span><div class="month-bar"><i class="${v<0?'neg':''}" style="width:${Math.abs(v)/max*100}%"></i></div><b class="${v<0?'negative':'positive'}">${pct(v)}</b></div>`).join('');}
function ledger(){const type=$('ledger-type').value,all=result[type],size=20,pages=Math.max(1,Math.ceil(all.length/size));page=Math.min(page,pages-1);let keys=type==='skips'?['hour','symbol','side','reason']:type==='closed'?['hour','symbol','side','qty','entry','exit','pnl','exitFee','reason']:['hour','symbol','side','action','notional','price','fee','pnl','reason'];const labels={hour:'UTC time',symbol:'Symbol',side:'Side',action:'Action',notional:'Notional',price:'Fill price',fee:'Fee',pnl:'Price PnL',reason:'Reason',qty:'Quantity',entry:'Entry',exit:'Exit',exitFee:'Exit fee'};
 $('ledger').innerHTML=all.length?`<table><thead><tr>${keys.map(k=>`<th>${labels[k]}</th>`).join('')}</tr></thead><tbody>${all.slice(page*size,(page+1)*size).map(r=>'<tr>'+keys.map(k=>{let v=r[k];if(k==='hour')v=new Date((result.epoch+v)*3600000).toISOString().slice(0,16).replace('T',' ');else if(typeof v==='number')v=['qty','price','entry','exit'].includes(k)?v.toLocaleString('en-US',{maximumFractionDigits:6}):money(v);return `<td class="${k==='pnl'?(r[k]<0?'negative':'positive'):''}">${esc(v??'—')}</td>`;}).join('')+'</tr>').join('')}</tbody></table>`:'<p class="hint">No events for this selection.</p>';
 $('page-count').textContent=`${all.length.toLocaleString()} events · ${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1;}
$('ledger-type').onchange=()=>{page=0;ledger();};$('prev').onclick=()=>{page--;ledger();};$('next').onclick=()=>{page++;ledger();};
function drawActive(){if(!result)return;const r=result.rows;if(active==='overview'){chart('equity-chart',r,[{key:'equity',name:'Equity',color:'#087e70'}],{baseline:result.config.capital});chart('dd-chart',r,[{key:'drawdown',name:'Drawdown',color:'#bd6374'}],{percent:true,baseline:0});}if(active==='attribution'){chart('pnl-chart',r,[{key:'pricePnl',name:'Price PnL',color:'#087e70'},{key:'funding',name:'Funding',color:'#527fcc'},{key:'fees',name:'Fees paid',color:'#bf8492'}],{baseline:0});chart('fund-chart',r,[{key:'funding',name:'Funding',color:'#527fcc'}],{baseline:0});chart('side-chart',r,[{key:'longPnl',name:'Long',color:'#087e70'},{key:'shortPnl',name:'Short',color:'#b780b4'}],{baseline:0});}if(active==='risk'){histogram();monthly();chart('exp-chart',r,[{key:'exposure',name:'Gross exposure',color:'#628b92'}],{baseline:0});}if(active==='trades')ledger();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-pressed',String(t===b));});document.querySelectorAll('.tab-content').forEach(t=>t.hidden=t.id!==active);drawActive();});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawActive,150);});
$('export').onclick=()=>{if(!result)return;const blob=new Blob([JSON.stringify({...result,dataSnapshot:{start:meta.start,end:meta.end,sources:meta.sources},hourConvention:'UTC timestamp = (epoch + hour) * 3600000 milliseconds',metricNotes:'Closing-event win rate and profit factor exclude entry fees and funding.'},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hl-backtest-${result.config.source}-${result.config.start}-${result.config.end}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const el of document.querySelectorAll('.chart'))el.innerHTML='<div class="placeholder">Your results will appear here.</div>';
try{const response=await fetch('./data/manifest.json');if(!response.ok)throw Error('Historical data could not be loaded. Please reload to retry.');meta=await response.json();coverage(true);hints();run();}catch(e){status.textContent=e.message;status.className='status error';}
